---
- name: Add SSH keys for elastic user
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    PH: prd   # or dev, whatever environment
  tasks:
    - name: Add SSH authorized keys
      copy:
        src: "{{ playbook_dir }}/../ssh_keys/{{ PH }}.pub"
        dest: "/home/elastic/.ssh/authorized_keys"
        owner: elastic
        group: elastic
        mode: '0600'
