---
- name: Add SSH keys for elastic user
  hosts: localhost
  connection: local
  become: yes
  gather_facts: false

  vars:
    PH: "{{ lookup('env','PH') }}"

  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/elastic/.ssh
        state: directory
        owner: elastic
        group: elastic
        mode: "0700"

    - name: Add SSH authorized keys
      authorized_key:
        user: elastic
        key: "{{ lookup('file', 'ssh_keys/{{ PH }}.pub') }}"
        state: present

